spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

app.seeders.enabled=false
app.mongo-init.enabled=false
app.scheduled-jobs.enabled=false
app.ai.enabled=true
app.external-services.enabled=true

spring.jpa.open-in-view=false
